### PR TITLE
fallback mechanism for old environments that doesn't support the `exports` field in `package.json`

### LINKED ISSUE #1: Doesn't seems to work with Svelte REPL
Reproduction: https://svelte.dev/repl/1e96cbd4bcd148e3b85a4c8ca76d7309?version=3.48.0

More details: https://github.com/orefalo/svelte-splitpanes/pull/39#issuecomment-1347089124

My guess is that REPL doesn't respect the `exports` field in `package.json`.

### PR DESCRIPTION
**Pull request by Tal500**
fixes #1

### CODE REVIEW

**Comment by Tal500** [comment]
@benmccann Do you agree with the fallback `export const DEV = false`?

**Comment by benmccann** [comment]
Yes, that's a good fallback. Wouldn't this new file also need to be added via `main` in `package.json`?

**Comment by Tal500** [comment]
> Yes, that's a good fallback. Wouldn't this new file also need to be added via `main` in `package.json`?

Well I guess that this suggestion was leading me to a better solution for browser detection! Just use the legacy "main" and the "browser" fields, and then we'd have compile time detection also for legacy bundlers!

See https://stackoverflow.com/questions/38055510/different-main-entry-point-in-package-json-for-node-and-browser#49204501

Notice: We need to check that Svelte REPL respects this behaviour.

I can do this probably in few hours from now.

What do you think @benmccann ?

**Comment by Tal500** [comment]
> 

OK, I did try to add the following to the `package.json` file:
```json
"browser": "./prod-browser.js",
"main": "./prod-ssr.js"
```

But this fails miserably since the `browser` tag isn't respected, at least not by Svelte REPL, as you can see [in my simple REPL](https://svelte.dev/repl/9046ed154ce940dfaae2048c80a212a9?version=3.55.1).

**Comment by Tal500** [comment]
> Yes, that's a good fallback. Wouldn't this new file also need to be added via `main` in `package.json`?

@benmccann Now when my experiments failed, I'll do your original suggestion, so I've added the "main" entry.

For the sake of the possible performance I've added also the `browser` entry, but I don't count on bundlers(i.e. Svelte REPL) to accept this, so the `main` entry-point is very careful as before.

A proof that this works on Svelte REPL now [is given here](https://svelte.dev/repl/59fe8cffed1743439a03df5c7a6167fa?version=3.55.1).

**Comment by Tal500** [comment]
Hi @benmccann again!
It has been awhile, can you merge the changes?
It will be easier for me to deprecate my `esm-env-robust` package.

**Comment by benmccann** [comment]
Hmm. That's quite disappointing that the REPL doesn't even support `browser`. Perhaps we should try fixing the REPL instead. I think it'd only be a few line change: https://github.com/sveltejs/sites/issues/134#issuecomment-1444393511

**Comment by Tal500** [comment]
> Hmm. That's quite disappointing that the REPL doesn't even support `browser`. Perhaps we should try fixing the REPL instead. I think it'd only be a few line change: [sveltejs/sites#134 (comment)](https://github.com/sveltejs/sites/issues/134#issuecomment-1444393511)

While this will be preferable, I think that this PR is good also for other platforms, if we want this package to be universal.

**Comment by Tal500** [comment]
> Hmm. That's quite disappointing that the REPL doesn't even support `browser`. Perhaps we should try fixing the REPL instead. I think it'd only be a few line change: [sveltejs/sites#134 (comment)](https://github.com/sveltejs/sites/issues/134#issuecomment-1444393511)

Please review my fix at sveltejs/sites#445.
Notice: This code works correctly in my local REPL dev server, outputting the correct envs:
```svelte
<script>
	import { BROWSER, DEV } from 'esm-env';
	let name = 'world';
</script>

<h1>Hello {name}!</h1>

<h2>Browser: {BROWSER}</h2>
<h2>Dev: {DEV}</h2>
```
Yielding:
```html
<body>
<h1>Hello world!</h1>
<h2>Browser: true</h2>
<h2>Dev: false</h2>
</body>
```

**Comment by benmccann** [comment]
Thanks for this! I'm torn on the idea of having a fallback. I think `exports` is supported so widely and universally today that it's pretty much unnecessary. It doesn't do any harm in some ways, but on the otherhand if there were any platform not supporting `exports` I'd rather just put more pressure on them to fix their stuff. Given that we have a fix for the REPL now, I think I'm going to go ahead and close this as I can't see where it'd be used

**Comment by Tal500** [comment]
> Thanks for this! I'm torn on the idea of having a fallback. I think `exports` is supported so widely and universally today that it's pretty much unnecessary. It doesn't do any harm in some ways, but on the otherhand if there were any platform not supporting `exports` I'd rather just put more pressure on them to fix their stuff. Given that we have a fix for the REPL now, I think I'm going to go ahead and close this as I can't see where it'd be used

Ah OK... So my package `esm-env-robust` will still be alive😬

**Pull request closed without merging**
